apiVersion: v1
kind: Service
metadata:
  name: app-pagamento-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
  selector:
    app: app-pagamento-pod